ODOICHON/frontend

- index.html
- src/main.tsx
- src/reset.scss
> chore : 폰트, 컬러 설정

- src/reset.scss
> Chore/#1 메인컬러 수정

- src/components/Terms/index.tsx
- src/pages/SignUp/index.tsx
클래스 추가 삭제 문법 setAttribute에서 classList로 변경
react-hook-form 필드에 terms추가, register 추가
<br>
> fix : classList 추가 문법 변경, Terms register 추가

- package.json
- src/App.tsx
- src/apis/axios.ts
- src/apis/login.ts
- src/hooks/useCheckAPI.tsx
- src/pages/Login/index.tsx
- src/pages/SignUp/index.tsx
- src/queryClient.ts
- src/store/userStore.ts
- src/types/user.d.ts
- yarn.lock
[로그인 페이지] Login API 연결 및 에러 핸들링
[회원가입 페이지] 이미 가입된 전화번호 에러 핸들링
[회원가입 페이지] [중복검사,인증 후 필드값 바뀌면 다시 검사,인증하도록 수정
<br>
> Feat/#18 로그인 API 연동 및 로직 구현

- src/App.tsx
- src/apis/login.ts
- src/apis/logout.ts
- src/assets/common/dropdown.svg
- src/assets/common/home.svg
- src/assets/common/log-out.svg
- src/components/AfterLogin/index.tsx
- src/components/AfterLogin/styles.module.scss
- src/components/BeforeLogin/index.tsx
- src/components/BeforeLogin/styles.module.scss
- src/components/Navbar/index.tsx
- src/components/Navbar/styles.module.scss
- src/queryClient.ts
- src/store/userStore.ts
- src/utils/utils.ts
로그인시 Navbar 적용
로그아웃 API 연동
<br>
> feat : 로그인시 Navbar 적용, 로그아웃 API 연동

- .gitignore
- src/App.tsx
- src/apis/axios.ts
- src/apis/login.ts
- src/apis/logout.ts
- src/apis/reissue.ts
- src/components/AfterLogin/index.tsx
- src/pages/Login/index.tsx
- src/pages/Main/index.tsx
- src/pages/SignUp/index.tsx
- src/types/userType.ts
> feat : 토큰 재발급 로직 구현

- .github/workflows/deploy.yml
- appspec.yml
implement github-actions CI/CD Pipeline
<br>
> chore : implement github-actions CI/CD Pipeline

- .github/workflows/deploy.yml
> fix : rename branch name

- src/pages/Main/index.tsx
- src/pages/Main/styles.module.scss
> fix : 메인페이지 컨텐츠 요소 클릭 가능하게 수정

- index.html
- src/apis/reissue.ts
- 토큰 만료 시 reissue API 전송되지 않았던 문제 해결
- 모바일에서 input 포커스 시 화면확대 방지 코드 추가
<br>
> Refactor/#45 토큰 만료 시 reissue API 전송되지 않았던 문제 해결

- src/App.tsx
- src/apis/uploadS3.ts
- src/components/BoardComponents/CommentDetail/index.tsx
- src/components/BoardComponents/CommentDetail/styles.module.scss
- src/components/BoardComponents/Comments/index.tsx
- src/components/BoardComponents/Comments/styles.module.scss
- src/main.tsx
- src/pages/AdminWrite/index.tsx
- src/pages/IntroBoard/index.tsx
- src/pages/Introduce/index.tsx
- src/utils/ScrollToTop.tsx
- S3 버킷 변경 및 페이지 이동 시 상단 스크롤 기능 추가
- 댓글 수정 기능 구현
- 댓글 400자 이상 등록 불가
- 게시글 수정 기능 구현
<br>
> Feat/#56 게시글 및 댓글 수정 기능 구현

- src/components/BoardComponents/Comments/index.tsx
- src/hooks/useWindowSize.ts
- src/reset.scss
- 댓글 작성 버그 수정
- 모바일에서 버튼 색상 수정 (파랑 -> 검정)
- 토글 메뉴 디바운스 1초 -> 0.5초
<br>
> Hotfix/#61 댓글 작성 버그 수정, 모바일 버튼 색상 수정

- src/Routes.tsx
- src/pages/Community/AdvertisementBoard/index.tsx
- src/pages/Community/AdvertisementBoard/styles.module.scss
- src/pages/Community/FreeBoard/index.tsx
- src/pages/Community/FreeBoard/styles.module.scss
- src/pages/Community/index.tsx
- src/pages/Community/styles.module.scss
커뮤니티 페이지 중첩 라우팅 경로 설계
pages/community를 레이아웃으로 두고 하위 페이지들을 Outlet으로 중첩라우팅
/community URL로 접근 시 /community/free_board 경로로 리다이렉트
<br>
> feat : 커뮤니티 라우팅 구조 설계

- src/pages/Community/Board/styles.module.scss
> style : 커뮤니티 페이지 반응형 UI 적용

- src/pages/Community/Detail/styles.module.scss
- 커뮤니티 게시글 상세 페이지 padding 간격 일정하게 수정
- 없음
> Design/#91 커뮤니티 상세 게시판 페이지 UI 수정

- src/App.tsx
- src/hooks/useAxiosInterceptor.ts
- src/pages/_layout.tsx
App.tsx에 작성된 axios interceptor 코드 분리
- App.tsx에 작성한 axios interceptor코드를 useAxiosInterceptor 훅으로 분리
- App.tsx에 작성한 스크롤, 토큰세팅 useEffect 코드를 최상단 레이아웃 컴포넌트인 _layout.tsx로 이동
> refact: axios interceptor 코드 커스텀훅으로 작성하여 컴포넌트와 분리

- package.json
- src/App.tsx
- yarn.lock
React GA 적용하기
- react-ga 라이브러리 설치
- App.tsx에 initialize 코드 적용
- .env에 GA 추적ID 추가
- 없음
> chore: React GA Initialize 코드 적용

- src/pages/Community/Board/index.tsx
- src/pages/Community/Detail/index.tsx
- src/pages/Community/Write/index.tsx
- src/pages/NotFound/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Write/index.tsx
> Feat/#129 애니매이션 적용 안된 페이지 애니메이션 적용

- src/constants/image.ts
- src/utils/Quill/imageHandler.ts
Lambda Edge를 사용한 On The Fly 방식의 이미지 리사이징 적용
- S3 업로드 후 받아오는 이미지 url을 cloudfront 이미지로 변경하기
- webp 이미지로 받아오면서 이미지 최적화
- 옵션 상수화
- 이후에 기존 이미지가 cloudfront로 적용되고난 후 옵션붙히기
> Feat/#124 이미지 리사이징 적용

- src/components/Community/Board/index.tsx
- src/components/Introduce/Quill/index.tsx
- src/components/Introduce/ReviewBoard/index.tsx
- src/components/Introduce/TrendBoard/index.tsx
- src/constants/image.ts
- src/pages/Main/index.tsx
- src/styles/reset.scss
썸네일 이미지 리사이징 적용
- 썸네일 이미지 url에 리사이징 옵션 적용
- 썸네일 이미지 handler에 cloudfront 적용하는 코드가 누락되어 추가
> Feat/#140 썸네일 이미지 리사이징 적용

- src/components/Board/CommentDetail/index.tsx
- src/components/Trade/Quill/index.tsx
- src/components/Trade/Quill/styles.module.scss
- src/constants/trade.ts
- src/pages/Trade/Write/index.tsx
- src/pages/Trade/Write/styles.module.scss
- src/styles/media.scss
- 빈집거래 글쓰기 페이지 퍼블리싱
- 글쓰기 페이지 퍼블리싱
- 모바일 기준 '업로드', '주소 찾기' 버튼 아이콘으로 변경
- X
- css 부분이 깔끔하지 못한 것 같아서 한번 피드백 부탁드립니다. ( 중복되는 스타일을 어떻게 없애야 할지 감이 잘 안옵니다😭 )
- quill 부분에서 스크롤을 내리면 quill bar가 분리되는? 현상이 일어납니다. 이 부분은 왜그런걸까요..?
> Feat/#150 빈집거래 글쓰기 페이지 퍼블리싱

- package.json
- public/mockServiceWorker.js
- src/apis/houses.ts
- src/components/Trade/AddressModal/index.tsx
- src/components/Trade/AddressModal/styles.module.scss
- src/components/Trade/Quill/index.tsx
- src/constants/trade.ts
- src/pages/Trade/Write/index.tsx
- src/pages/Trade/Write/styles.module.scss
- src/types/Board/tradeType.ts
- src/types/user.d.ts
- src/utils/utils.ts
- yarn.lock
- 빈집거래 글쓰기 페이지 관련 작업
- 빈집거래 글쓰기 페이지 api 연동 ( 임시저장 X )
- 빈집거래 api 응답 type 수정
- 빈집거래 글쓰기 유효성 검사 함수 추가
- 전역관리상태 user에 속성 추가 -> userType 추가함 ( 유저가 공인중개사인지 아닌지 확인하는 값 )
> Feat/#152 빈집거래 글쓰기 페이지 API 연동

- src/components/Trade/Info/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Board/styles.module.scss
- src/pages/Trade/Write/index.tsx
- src/types/Board/tradeType.ts
- src/utils/utils.ts
- 로그인 여부에 따른 리다이렉트
- 매물 특징 리스트 추가
- 공인중개사 여부에 따른 태그 분류
- tradeBoardDetailType 에 recommendedTag,recommendedTagName 타입 빠져서 추가
> Feat/#156 빈집거래 상세 페이지 수정 및 기능 추가

- src/utils/utils.ts
> Fix/#161 입주가능 여부에 대한 함수 수정

- src/Routes.tsx
- src/apis/login.ts
- src/components/Common/Footer/index.tsx
- src/components/Common/Footer/styles.module.scss
- src/components/Terms/AgentTerm.tsx
- src/components/Terms/MarketingTerm.tsx
- src/components/Terms/PrivacyTerm.tsx
- src/components/Terms/ServiceTerm.tsx
- src/components/Terms/index.tsx
- src/components/Trade/AddressModal/index.tsx
- src/pages/AgentSignUp/index.tsx
- src/pages/Login/index.tsx
- src/pages/SignUp/AgentSignUp/index.tsx
- src/pages/SignUp/AgentSignUp/styles.module.scss
- src/pages/SignUp/index.tsx
- src/pages/SignUp/styles.module.scss
- src/pages/Trade/Write/index.tsx
- src/queryClient.ts
- src/styles/reset.scss
- src/types/signUp.ts
- src/types/user.d.ts
공인중개사 회원가입 페이지 구현
- 공인중개사 회원가입 페이지 UI 구현
- 공인중개사 회원가입 API 연동
- 공인중개사 회원가입 구현 완료 
- 없음
> Feat/#166 공인중개사 회원가입 페이지 UI 및 기능 구현

- public/mockServiceWorker.js
- src/Routes.tsx
- src/components/Board/CommentDetail/index.tsx
- src/components/MyPage/MyPageNavbar/index.tsx
- src/components/MyPage/MyPageNavbar/styles.module.scss
- src/pages/Mypage/index.tsx
- src/pages/Mypage/styles.module.scss
-  마이페이지 메뉴바 구현 ( 데스크톱 )
- 마이페이지 메뉴바 라우팅 경로 지정 ( 피그마 확인 부탁드려요! )
> feat: 마이페이지 메뉴바 UI 구현 ( 데스크톱 )

- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Write/index.tsx
- src/pages/Trade/index.tsx
오타 수정과 워딩 통일 작업
- 중계 프로세스 -> 중개 프로세스 오타 수정
- 빈집중개 -> 빈집거래 워딩 통일
- 없음
> Hotfix/#175 오타, 워딩 수정 (Production)

- .github/workflows/deploy.yml
개발용 서버 Code Deploy 깃허브 액션 코드 작성
- main과 develop 브랜치 별로 cd 코드 분리
- 깃허브 Secret키 변경 (노션 참고)
- .env 변경 (노션 참고)
- 없음
> Hotfix/#180 개발용 서버 Code Deploy 코드 작성 (Development)

- .github/workflows/deploy.yml
> fix: github actions 코드 수정

- .github/workflows/deploy.yml
개발용 서버 Code Deploy 깃허브 액션 코드 작성
- main과 develop 브랜치 별로 cd 코드 분리
- 깃허브 Secret키 변경 (노션 참고)
- .env 변경 (노션 참고)
- 없음
> Hotfix/#180 개발용 서버 Code Deploy 코드 작성 (Production)

- src/apis/houses.ts
- src/components/Trade/Quill/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Board/styles.module.scss
- src/pages/Trade/Write/index.tsx
- src/pages/Trade/index.tsx
- src/types/Board/tradeType.ts
- 빈집거래 상세 페이지 수정 기능 구현
- 빈집거래 상세 페이지 삭제 기능 구현
- 소개 페이지 react-query refetch 부분 수정
> feat: 빈집거래 상세 페이지 수정/삭제 기능 구현

- src/Routes.tsx
- src/pages/Mypage/home/index.tsx
- src/pages/Mypage/trade/myself/index.tsx
- src/pages/Mypage/trade/saves/index.tsx
- src/pages/Mypage/trade/scrap/index.tsx
-  마이페이지 관련 페이지 컴포넌트들에 적용되어 있던 Lazy Loading 제거
✔️ check list
> Refactor/#210 마이페이지 관련 Lazy Loading 제거

- src/Routes.tsx
- src/components/MyPage/MyPageNavbar/index.tsx
- src/pages/Mypage/community/likes/index.tsx
- src/pages/Mypage/community/likes/styles.module.scss
- src/queryClient.ts
- query key 상수 값 추가
- router 설정
- '내가 좋아요한 게시글' 페이지 구현 ( api 연동 포함 )
> Feat/#199 마이페이지 '내가 좋아요 한 게시글' 구현

- src/Routes.tsx
- src/pages/MyPage/community/comments/index.tsx
- src/pages/MyPage/community/comments/styles.module.scss
- src/pages/MyPage/community/likes/index.tsx
- src/pages/MyPage/community/likes/styles.module.scss
- src/pages/MyPage/community/write/index.tsx
- src/pages/MyPage/community/write/styles.module.scss
- src/pages/MyPage/home/index.tsx
- src/pages/MyPage/home/styles.module.scss
- src/pages/MyPage/index.tsx
- src/pages/MyPage/setting/CertificateMember/index.tsx
- src/pages/MyPage/setting/CertificateMember/styles.module.scss
- src/pages/MyPage/setting/EditMember/index.tsx
- src/pages/MyPage/setting/EditMember/styles.module.scss
- src/pages/MyPage/setting/EditPassword/index.tsx
- src/pages/MyPage/setting/EditPassword/styles.module.scss
- src/pages/MyPage/setting/WithdrawalFromMembership/index.tsx
- src/pages/MyPage/setting/WithdrawalFromMembership/styles.module.scss
- src/pages/MyPage/setting/index.tsx
- src/pages/MyPage/setting/styles.module.scss
- src/pages/MyPage/styles.module.scss
- src/pages/MyPage/trade/myself/index.tsx
- src/pages/MyPage/trade/myself/styles.module.scss
- src/pages/MyPage/trade/saves/index.tsx
- src/pages/MyPage/trade/saves/styles.module.scss
- src/pages/MyPage/trade/scrap/index.tsx
- src/pages/MyPage/trade/scrap/styles.module.scss
MyPage 폴더명 대소문자로 인한 build 실패
- MyPage 폴더명 대소문자 변경
- Mypage -> MyPage
> !HOTFIX: MyPage 폴더명 대소문자 수정

- src/pages/Introduce/Board/index.tsx
- 오도이촌 소개 페이지 -> 트렌드 상세 페이지에 '좋아요', '댓글' 기능 추가
- 댓글 기능 제거하기
> Feat/#238 트렌드 상세 페이지에 '좋아요' 기능 추가

- src/components/Board/CommentDetail/index.tsx
- src/components/Board/CommentDetail/styles.module.scss
- src/hooks/useToastMessageType.ts
- src/pages/Introduce/Board/index.tsx
- 게시글 삭제 여부를 위한 모달창 타입 추가
- 게시글 삭제 시, 삭제 여부 확인 모달창 띄우기 
- 댓글 수정중일 때, '수정' 버튼 주말내집 메인 컬러(주황색)으로 활성화
> Feat/#240 트렌드 후기 콘텐츠 삭제 시, 삭제 여부 확인 모달창 띄우기

- src/hooks/useToastMessageType.ts
- src/pages/Community/Board/index.tsx
- src/utils/utils.ts
- 커뮤니티 페이지에서 검색 시, '안녕 ㅇ'과 같이 완성되지 않은 검색어에 대해서 모달창이 필요
- 문자열에 자음 또는 모음이 단독으로 포함되는 경우 확인하는 함수 구현
- 잘못된 검색어 입력 시, 검색 에러 모달창 띄우기
- 자음, 모음 판별하는 함수명 고민
> Feat/#244 커뮤니티 페이지에서 검색 시, 글자 조합이 완성되지 않은 경우 모달창 띄우기

- src/components/Terms/MarketingTerm.tsx
- src/pages/SignUp/AgentSignUp/index.tsx
- src/pages/SignUp/index.tsx
회원가입 이용 약관에서 마켓팅 -> 마케팅 워딩 수정
- 일반 회원 가입 페이지에서 마켓팅 워딩 수정
- 공인중개사 회원 가입 페이지에서 마켓팅 워딩 수정
- 마케팅 동의 모달 컴포넌트에서 워딩 수정
-
> fix: 마켓팅 -> 마케팅 워딩 수정

- src/pages/Main/index.tsx
메인페이지 트렌드 버튼 트랜드 -> 트렌드 워딩 수정
- pages/Main.tsx에서 트랜드 -> 트렌드 워딩 수정
-
> fix: 메인페이지 트랜드 -> 트렌드 워딩 수정

- src/components/Board/Comments/index.tsx
- src/components/Board/Comments/styles.module.scss
> Design/#255 댓글 버튼 UI 수정

- .github/workflows/deploy.yml
- appspec.yml
- 개발환경과 운영환경의 저장 위치가 달라서 환경에 맞게 appspec.yml 수정
- 노션에 Deploy Secret Key 페이지에 key 추가
> chore: 운영, 개발 환경에 따른 appspec.yml, deploy.yml 수정

- .github/workflows/deploy.yml
> docs: deploy.yml 수정

- src/components/Common/Footer/index.tsx
- src/components/Common/Navbar/index.tsx
- src/components/Common/ToggleMenu/index.tsx
- src/pages/MyPage/home/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Process/index.tsx
- src/pages/Trade/Write/index.tsx
- src/pages/Trade/index.tsx
- src/utils/utils.ts
> design: 키워드 변경 (빈집거래 -> 농가거래)

- src/pages/Trade/Write/index.tsx
- src/pages/Trade/Write/styles.module.scss
- src/types/Board/tradeType.ts
- src/utils/utils.ts
- 농가거래 등록 페이지에서 거래 유형 추가
- 등록전 필수 사항 체크 하는 함수 수정 -> 준공연도, 매물 용도 선택사항으로 변경
> Feat/#284 농가 거래 등록 페이지에 등록해야하는 목록 수정 및 기능 추가

- src/pages/Trade/Write/index.tsx
- src/types/Board/tradeType.ts
공인중개사 상세 설명 타입 추가
- `TradeBoardForm` 타입과 `TradeBoardDetailType`에 `agentDetail`필드 추가
-
> feat: 공인중개사 상세 설명 타입 추가

- src/pages/Trade/Write/index.tsx
- src/utils/utils.ts
- 농가 거래 작성 페이지에 '상세 설명' 목록 추가
- 상세 설명 유효성 검사 로직 추가
> Feat/#291 농가 거래 작성 페이지에 '상세 설명' 목록 추가 ( 공인중개사 일 때 )

- src/components/Trade/Info/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Board/styles.module.scss
- 농가 거래 상세 페이지에서 UI를 수정합니다.
- 매물 특징 박스 background 변경 및 border 추가
- 공인중개사 매물일 경우 공인중개사의 정보를 따로 제공하는 박스로 분리
- 가격 보여주는 부분 만원 단위로 변환하는 함수로 매핑
> feat: 농가 거래 상세 페이지 UI 수정

- src/components/Trade/AddressModal/index.tsx
주소 찾기 모달을 닫는 기능을 추가합니다.
- AddressModal 컴포넌트에서 외부 영역을 클릭할 시 모달을 닫는 로직을 추가합니다.
> feat: 주소 찾기 모달 닫는 기능 추가

- .github/workflows/deploy.yml
Code Deploy에서 application name을 github secret으로 등록
- Code Deploy에서 application name을 github secret으로 등록
> 개발서버 관련 github action 코드 수정
