ODOICHON/frontend

- src/App.tsx
- src/apis/login.ts
- src/apis/reissue.ts
- src/components/Navbar/index.tsx
- src/components/ToggleMenu/index.tsx
- src/pages/Login/index.tsx
- src/pages/Mypage/index.tsx
- src/pages/SignUp/index.tsx
- src/store/userStore.ts
- src/types/user.d.ts
refresh token 저장 방식 변경에 따른 프론트엔드 코드 수정
- Token 타입 변경 (refresh token 삭제)
- 로그인 api header에 withCredentials 추가
- reissue api 코드 수정 (refresh token 삭제)
<br>
> refact : 프론트엔드 refresh token 저장 방식 변경

- .gitignore
- src/components/BoardComponents/Like/index.tsx
- src/pages/Introduce/index.tsx
- src/pages/Main/index.tsx
게시글 리스트 조회 API 명세 변경에 따른 메인페이지, 오도이촌 소개 페이지 게시글 리스트 조회 API 호출 코드 수정
- /api/v1/boards의 params부분을 category -> prefix로 수정
로그인 하지 않은 유저 좋아요 여부 조회 버그 수정
- 유저의 좋아요 여부 확인 API 호출 부분에 `enabled: !!user`를 추가하여 로그인 하지 않았을 시 API 호출 자체를 하지 않도록 수정
<br>
- src/pages/Introduce/index.tsx
- src/pages/Main/index.tsx
- .gitignore (.eslintcache 파일 추가)
<br>
> hotfix : 게시글 리스트 조회 API 변동에 따른 운영환경 API 호출 코드 수정 핫픽스

- src/pages/Community/Detail/styles.module.scss
- src/pages/Introduce/Board/styles.module.scss
- src/pages/Main/styles.module.scss
- src/reset.scss
메인페이지와 소개 게시글의 배너 높이와 게시글 폰트 사이즈가 너무 크다는 피드백이 있어 이에 따른 CSS 수정.
- 메인페이지 배너 이미지, 소개 게시글 상세 페이지 배너 이미지 height값 수정
- heigth값을 viewport height로 어느 디바이스에서든 동일한 높이로 보이도록 수정
- 게시글 상세 페이지와 텍스트 에디터 (Quill)의 폰트 사이즈 전반적으로 수정
- 전반적으로 0.2~0.5rem 정도 크기 축소
> Design/#86 배너 이미지 크기 수정, 게시글 폰트 사이즈 수정

- src/pages/Introduce/index.tsx
- src/pages/Main/index.tsx
- src/types/boardType.ts
- 게시글 데이터 가져오는 새로운 api 적용
- 메인 페이지 / 오도이촌 소개 페이지 게시글 정보 불러오기 api 적용
- 메인 페이지 / 오도이촌 소개 페이지 새로운 api 적용함에 따라 코드 수정
- 새로운 api 응답값 Type 추가 => 게시글 type 관련
> Feat/#90 메인페이지 게시글 api 연동

- src/components/Terms/styles.module.scss
회원가입 페이지에서 커뮤니티 페이지 이동시 생기는 리스트 스타일 초기화 버그 수정
- 회원가입 페이지 -> 커뮤니티 페이지 이동 시  전역으로 ul태그의 해당 스타일이 상속받는 것이 확인됨.
- 해당 스타일 코드는 components/Terms의 스타일 코드로, 회원가입 페이지의 약관 컴포넌트 스타일 코드이다.
- 해당 스타일 코드에서 아래와 같이 전역적으로 태그에 대한 스타일을 적용하고 있음.
```css
article {
margin-bottom: 1rem;
line-height: 1.5rem;
}
ul {
padding-left: 1rem;
list-style: disc;
}
ol {
list-style: decimal;
padding-left: 1rem;
}
```
- 따라서 태그 자체에 스타일을 적용하는 것이 아닌 특정 태그의 자손태그로서의 스타일로 변경 후 적용
```css
.termsContainer {
...
& article {
margin-bottom: 1rem;
line-height: 1.5rem;
}
& ul {
padding-left: 1rem;
list-style: disc;
}
& ol {
list-style: decimal;
padding-left: 1rem;
}
}
```
- 없음
> fix: 회원가입 페이지에서 커뮤니티 페이지 이동시 생기는 리스트 스타일 초기화 버그 수정

- src/pages/Community/Detail/styles.module.scss
- src/pages/Introduce/Board/styles.module.scss
- src/pages/Main/index.tsx
- src/pages/Main/styles.module.scss
- src/queryClient.ts
- src/reset.scss
모바일 사이즈에서 폰트 사이즈 조정
- 모바일 사이즈에서 body의 font-size를 53.125%로 수정 (1rem = 9px)
- 메인페이지 소개글 모바일 화면에서 폰트사이즈 크기 증가
- Quill 게시글 / 게시글 상세 페이지에서 blockquote 태그 인용문 스타일 추가
> Design/#105 모바일 폰트 사이즈 조정

- package.json
- src/apis/uploadS3.ts
- src/components/Community/Quill/index.tsx
- src/components/Community/Quill/styles.module.scss
- src/components/Introduce/Quill/index.tsx
- src/components/Introduce/Quill/styles.module.scss
- src/components/Trade/SearchBar/styles.module.scss
- src/hooks/useQuillModules.ts
- src/pages/Trade/styles.module.scss
- src/styles/editor.scss
- src/styles/reset.scss
- src/utils/Quill/imageHandler.ts
- yarn.lock
게시글 에디터 높이가 현재는 오버 시 scroll이 되는 형식인데, 높이가 늘어나는 형식으로 변경
- Community 게시글 작성 페이지 코드 구조 변경, CSS 수정
- Introduce 게시글 작성 페이지 코드 구조 변경, CSS 수정
- 코드 구조 변경 사항
- 기존 <labelSection>과 <ContentSection>을 구분하여 태그 구조를 쌓았음.
- 리팩토링 이후, <inputWrapper>안에서 label과 content를 포함하는 구조로 리팩토링
- Quill 에디터에 이미지 리사이즈 모듈 추가
- `yarn add quill-image-resize-module-ts` 패키지 설치 후 적용
- 사용자가 에디터에서 이미지 업로드 후 자유롭게 이미지 사이즈 조절 가능
> Design/#132 게시글 에디터 높이 CSS 수정

- index.html
- src/components/Community/Quill/styles.module.scss
- src/components/Introduce/Quill/styles.module.scss
- src/styles/editor.scss
- src/styles/reset.scss
게시글 작성에서 화면 스크롤 시 에디터 툴바 화면에 고정하도록 CSS 수정
- ql-toolbar를 `position: sticky`로 하고, 소개 게시글과 커뮤니티 게시글의 top이 다르므로 (navbar 때문) 각각 스타일 코드에서 top 값을 적용시켰습니다.
- 게시글의 이미지의 max-height를 100%로 수정했습니다.
> design: 게시글 작성에서 스크롤 시 에디터 툴바 화면에 고정

- package.json
- src/App.tsx
- src/hooks/useReactGA.ts
- yarn.lock
GA Universe가 2023/07/01 부로 지원하지 않게 됨으로 React GA4로 마이그레이션
- react-ga 라이브러리 uninstall
- react-ga4 라이브러리 설치
- GA4 세팅 커스텀 훅인 useReactGA 코드 생성
없음
> fix: React GA4 적용

- package.json
- src/apis/uploadS3.ts
- src/components/Introduce/Quill/index.tsx
- src/utils/Quill/imageHandler.ts
- yarn.lock
이미지 업로드 시 중복된 이름의 이미지일 경우 이전 이미지가 보이는 현상 발생
따라서 이미지 이름을 고유값으로 적용
- uuid 라이브러리를 활용해서 이미지 고유 이름 생성
- 없음
> Hotfix/#144 이미지 업로드 시 이미지 이름 고유값으로 수정

- src/components/Board/Like/index.tsx
- 좋아요 낙관적 업데이트 리펙토링
- 좋아요 버튼 누르면 즉각 표시 로직 중복로직 제거
- 좋아요 수 업데이트 낙관적 적용 안된거 적용
- 기존 로직에서 좋아요 수는 좋아요 버튼이 낙관적으로 업데이트가 되고 실제 api 요청을 성공하면 onSettled 옵션을 통해 retch를 하고 업데이트 된 값을 가지고 렌더링 하다보니 좋아요 수는 낙관적으로 업데이트가 진행되지 않더라구요! 그래서 적용을 해봤습니다. 커밋을 2개로 적용하기 전과 후로 나눠놨고 확인 가능하도록 해놨습니다!
- 좋아요 버튼은 낙관적이 되는데, 좋아요 수는 낙관적이 안되면 사용자 경험에 좋지 않을 것 같아서 작업했습니다. 그렇다면 내부적인 로직으로 봤을 때, api요청을 더 하게 되는가? 그렇지 않습니다. 결과적으로 같은 결과는 내는데 동일한 api 호출 횟수로 요청합니다. 좋아요 수를 낙관적 업데이트 한다고 해서 성능이 나빠지지는 않는다고 생각합니다!
- X
> Refact/#148 좋아요 로직 리펙토링 ( 낙관적 업데이트 )

- src/components/Common/ui/Button/index.tsx
- src/components/MyPage/MyTradeCard/index.tsx
- src/components/MyPage/MyTradeCard/styles.module.scss
- src/components/Trade/Info/index.tsx
- src/components/Trade/Quill/index.tsx
- src/pages/Mypage/trade/myself/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/Board/styles.module.scss
- src/pages/Trade/Write/index.tsx
- src/pages/Trade/index.tsx
- src/types/Board/boardType.ts
- src/utils/utils.ts
빈집거래 페이지에서 상단 필터링 (유형, 지역, 검색어) 적용 시 화면에 반영되지 않는 버그 해결
- 초기값을 fetch하여 state에 setState하는 useQuery와 다음 페이지의 내용을 기존 state 배열에 업데이트하는 useQuery를 분리 (예전 코드로 롤백)
- 빈집거래 게시글 작성 페이지 리팩토링 (유효성 검사 및 대체 텍스트 추가)
- 공인중개사 아닐 시 공인중개사 정보 표기하지 않도록 수정
- 게시글 상세 페이지에 상단 태그값에서 매물유형 정보 표기하지 않도록 수정
- 게시글 상세 페이지에서 상단 태그값에 거래완료 게시글에 대한 표기 및 스타일링 수정
- 마이페이지에서 내 매물 관리 페이지의 page값 초기값 수정 (기존 0이었는데 1로 수정)
- 마이페이지에서 내 매물 관리 페이지의 페이지네이션 값 캐싱되어 화면에 업데이트 되지 않는 버그 수정
- 마이페이지에서 내 매물 관리 페이지의 게시글 클릭 시 게시글 상세 페이지로 이동되도록 구현
> Fix/#190 빈집거래 페이지 상단 필터링(유형, 위치, 검색)에 따라 결과에 제대로 업데이트 되지 않는 버그 수정

- src/apis/houses.ts
- src/components/MyPage/DealStateModal/index.tsx
빈집거래 게시글 상태변경 시 구매자 주말내집 닉네임 에러 핸들링 처리
- 빈집거래 상태 변경 시 존재하지 않는 아이디일 경우 서버에서 던져주는 에러메시지 알림
- 빈집거래 상태 변경 시 전화번호 형식 처리 및 유효성 검사 추가
-
> fix: 빈집거래 게시글 상태변경 시 에러 핸들링 처리

- src/pages/Community/Board/index.tsx
- src/pages/Community/Board/index.tsx 에서 `<CommunityBoard/>` 컴포넌트 props인 prefixCategory 값을 잘못 전달하고 있었음.
따라서, 수정해서 올바른 props 값을 넘겨줘서 해결
> Fix/#208 커뮤니티 페이지에서 게시글 클릭 시, 게시글 상세 페이지로 이동 안되는 버그 수정

- src/Routes.tsx
- src/components/Trade/ScrapIcon/index.tsx
- src/pages/Mypage/home/index.tsx
- src/pages/Mypage/trade/scrap/index.tsx
- src/queryClient.ts
- 스크랩을 누르면 관련된 캐싱 데이터들 동기화 하기
- Querykey 추가
- refechQueires 사용해 데이터 동기화
- route 경로 대소문자 변경 Mypage -> MyPage
> Fix/#226 스크랩 캐싱 안되는 부분 추가 구현

- src/components/Community/Board/index.tsx
- src/components/Community/Quill/index.tsx
- src/components/Introduce/Quill/index.tsx
- src/pages/Community/Detail/index.tsx
- src/pages/Community/Detail/styles.module.scss
- src/styles/editor.scss
- src/utils/utils.ts
- 자유게시판 말머리 미 선택시, category 값 'EMPTY' 로 설정
- 백엔드 ENUM 맞추기 위해서 'EMPTY'로 설정
- 게시판에 a태그 관련 색상 메인컬러로 변경
- category 값은 백엔드에서 ENUM 값으로 관리중, 따라서 Board API 명세서에 ENUM 종류 확인 가능하도록 요청
- 현재 category 미선택 시, 게시글 말머리 표시는 '[전체]'로 표기하도록 했다.
- 말머리 표시가 아예 안나오게 할지 물어보기 또는 다른 키워드로 할지
- 피그마에는 이 부분에 대한 디자인 없음
[기획팀 답변]
- 키워드 없이 제목으로 시작하기
수정 후
- 프론트에서 category 값 상수화 해서 사용하는게 좋아보인다. ( TODO 키워드로 검색해서 부분 고치기 )
- 어떤 식으로 상수화를 해서 관리할지 고민
> Feat/#246 자유게시판 게시글 작성시 말머리 미선택해도 게시글 작성 가능하게 구현

- src/components/Board/CommentDetail/index.tsx
- src/components/Board/Comments/index.tsx
- src/hooks/useToastMessageType.ts
- 홍보, 자유게시판 댓글 삭제 시, 삭제되었다는 모달창 띄우기
- 댓글 삭제 시, 모달창에 띄어지는 상수 값 추가
- useModalState 훅에서 handleModalClose에 함수 파라미터 받도록 추가
> Feat/#248 홍보, 자유 게시판 댓글 삭제 시, 모달창 띄우기

- src/apis/uploadS3.ts
- src/components/Community/Board/index.tsx
- src/components/Community/Quill/index.tsx
- src/components/Introduce/Quill/index.tsx
- src/components/Introduce/ReviewBoard/index.tsx
- src/components/Introduce/TrendBoard/index.tsx
- src/components/Trade/Quill/index.tsx
- src/hooks/useQuillModules.ts
- src/pages/Community/Detail/index.tsx
- src/pages/Main/index.tsx
- src/pages/Trade/Write/index.tsx
- src/store/imageStore.ts
- src/utils/Quill/getNotUsedImageUrl.ts
- src/utils/Quill/imageHandler.ts
- src/utils/utils.ts
게시글 작성 중 페이지 이탈 시 업로드된 이미지를 S3에서 삭제합니다.
게시글 업로드 시 실제로 사용되는 이미지를 제외하고 에디터에서 지웠던 이미지에 대해 S3에서 삭제합니다.
기존에 적용했던 CloudFront 관련 코드를 제거합니다.
- 게시글 작성 시 업로드한 이미지의 URL을 저장하는 imageStore 전역 변수를 선언했습니다.
- 게시글 업로드 시 imageStore와 작성한 게시글의 이미지를 비교하여 삭제된 이미지들에 대해 S3에서 삭제하도록 했습니다.
- 게시글 작성 중 페이지를 이탈했을 때 게시글에 작성된 이미지들을 S3에서 삭제하도록 했습니다.
- 기존에 적용했던 CloudFront 관련 코드를 제거합니다.
- 이미 업로드된 게시글의 이미지는 사용자가 추후에 게시글 수정이나 게시글 삭제하여도 S3에서 삭제되지 않도록 하였습ㅁ니다.
> 게시글 작성 시 S3 이미지 관련 기능 추가

- src/components/Trade/Dropdown/index.tsx
- src/components/Trade/SearchBar/index.tsx
- src/constants/trade.ts
- src/pages/Trade/index.tsx
- src/types/Board/tradeType.ts
- src/utils/utils.ts
- 기존의 유형 타입을 거래 타입으로 변경
- 새로운 유형 타입 추가
- 기존 "유형" 타입을 "거래" 타입으로 변경
- 단순 보여지는 텍스트를 "거래"로 변경함
- 새로운 "유형" 타입 추가
- HouseType 생성
> feat: 농가 거래 페이지 검색 필터에서 새로운 유형 타입 추가 & 기존 유형 타입을 거래 타입으로 변경

- src/components/Trade/Board/index.tsx
- src/components/Trade/Info/index.tsx
- src/pages/Trade/Board/index.tsx
- src/pages/Trade/index.tsx
- src/types/Board/tradeType.ts
- src/utils/utils.ts
- 농가 거래 상세 페이지에서 유형 정보를 추가합니다.
- 농가 거래 게시글 제목에 유형 말머리를 추가합니다.
- TradeBoard 타입에 HouseType 필드 추가
- 농가 거래 상세 페이지에서 유형 정보 추가
- 농가 거래 게시글 제목에 유형 말머리 추가
- 농가 거래 상세 페이지 정보 UI 순서 수정
> 농가 거래 상세 페이지에서 유형 정보 추가 및 게시글 제목 말머리에 유형 추가

- src/apis/reissue.ts
refresh 토큰 만료 시 사용자에게 서버 응답Alert를 보여주지 않도록 설정합니다.
- refresh 토큰 만료 시 사용자에게 Alert를 보여주지 않도록 catch문 수정
-
> fix: refresh 토큰 만료 시 사용자에게 Alert를 보여주지 않도록 설정합니다.

- package.json
- src/hooks/useSwiperRef.ts
- src/pages/Introduce/index.tsx
- src/pages/Main/index.tsx
- src/pages/Trade/Board/index.tsx
- yarn.lock
메인페이지 오도이촌 소개, 커뮤니티 콘텐츠 카드 슬라이더 swiper를 loop로 설정하여 순환하도록 설정하려 했으나
현재 슬라이더를 넘기는 좌우 버튼을 swiper 외부로 분리하여 ref로 사용하는 방법과 loop 옵션을 같이 사용하는 경우 제대로 동작하지 않는 이슈가 있습니다.
순환하도록 설정하는 것은 나중으로 미루고 버전 업데이트와 swiper 훅을 분리하는 것을 구현했습니다.
- swiper 버전 업데이트 v9 -> v11
- swiper 초기화 부분 커스텀훅으로 분리
-
> fix: 메인페이지 오도이촌 소개, 오도이촌 커뮤니티 콘텐츠 카드 슬라이더 순환하도록 수정

- src/pages/MyPage/home/index.tsx
- src/pages/MyPage/trade/scrap/index.tsx
TradeBoard에 houseType prop이 생김에 따라 props 전달이 되지 않은 컴포넌트 수정
- 마이페이지에서 TradeBoard 컴포넌트를 사용하는 부분에 houseType prop 추가
> TradeBoard에 houseType prop이 생김에 따라 props 전달이 되지 않은 컴포넌트 수정
